# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/project

    steps:
        # Log the current branch
        - run:
            name: Show current branch
            command: echo ${CIRCLE_BRANCH}
        # Install project dependencies
        - run:
            name: Install local dependencies
            command: yarn install
        # Install project dependencies
        - run:
            name: Build project
            command: yarn build
